---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Create a VM From a template
      vmware_guest:
        hostname: 10.4.44.11
        username: administrator@pac.lab
        password: Password#1
        validate_certs: False
        name: test-vm
        state: poweredon
        template: UbuntuTmpl
        disk:
        - size_gb: 10
          type: thin
          datastore: prod_ds
        hardware:
          memory_mb: 512
          num_cpus: 1
        networks:
        - name: VM Network

        wait_for_ip_address: yes
