---
- hosts: all
  remote_user: root
  become: yes
  connection: local
  tasks:
   - vsphere_guest:
       vcenter_hostname: 10.4.44.11
       username: administrator@pac.lab
       password: Password#1
       validate_certs: False
       guest: test-vm
       from_template: yes
       template_src: UbuntuTmpl
       cluster: cluster
       esxi:
          datacenter: Datacenter
          hostname: 10.4.44.101
