---
- hosts: all
  remote_user: root
  become: yes
  connection: local
  tasks:
   - vsphere_guest:
       vcenter_hostname: <vcenterIP>
       username: <vcenterUser>
       password: <vcenterPass>
       validate_certs: False
       guest: test-vm
       from_template: yes
       template_src: UbuntuTmpl
       cluster: cluster
       esxi:
          datacenter: Datacenter
          hostname: <host IP>
